name: "Run"
on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.7
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - run: julia --project=. -e "using Pkg; Pkg.instantiate()"
        shell: sh
      - run: julia --project=. -e "using CondaPkg; CondaPkg.resolve()"
        shell: sh
      - uses: actions/cache@v3
        with:
          path: |
            ~/.julia/artifacts
            ~/.julia/packages
            .CondaPkg
          key: ${{ runner.os }}-v1
      - run: julia --project=. bulkreport.jl
        shell: sh
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: reports
          publish_branch: reports
          force_orphan: true
